title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
theme: jekyll-theme-cayman

conference_name: The 3rd Workshop on Personal Intelligence with Generative AI
# conference_www: "on the Web Conference 2025 (WWW'25)"
conference_www: "Venue & Date: TBD"
# conference_venue: "Leo 3 @ Resorts World Sentosa Convention Centre, Singapore"
# conference_time: "Monday 13 May 2024, 9:00 AM - 12:35 PM"
# conference_venue: ""
# conference_intro: "Will be held in 2024"
conference_intro: ""

github:
  zip_url: http://www.google.com

collections:
  organizers:
    output: true
  speakers:
    output: true
